name: sigclust
channels:
  - conda-forge
  - mosek
dependencies:
  - matplotlib
  - numpy
  # - numpy=1.21.*  # as of 8/1/2022, numba wants <=1.21
  - pandas
  - python
  - scikit-learn
  - scipy
  - seaborn
  - cvxpy
  - cvxopt
  - networkx
  - tqdm
  - numba
  - ipykernel
  - ipywidgets
  - toolz
  - matplotlib-label-lines
  - mosek
  - pytest
