name: sigclust
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy=1.21.*  # as of 8/1/2022, numba wants <=1.21
  - pandas
  - python>=3.8
  - scikit-learn
  - scipy
  - seaborn
  - cvxpy
  - networkx
  - tqdm
  - numba
  - ipykernel
  - toolz
  - matplotlib-label-lines
